Repository reactiveui/ReactiveUI.Validation, pull requests merged in 2020-10, with the labels that each got.

#110 housekeeping: Release version 1.6
  version.json
Labels: release

#112 housekeeping: Lock GitHub actions to major version.
  .github/workflows/ci-build.yml
Labels: release

#113 housekeeping: Fix invalid environment in github action
  .github/workflows/ci-build.yml
Labels: release

#114 Support Binding to IReactiveObject's
  src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt
  src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt
  src/ReactiveUI.Validation.Tests/Models/ISampleViewModel.cs
  src/ReactiveUI.Validation.Tests/Models/SampleView.cs
  src/ReactiveUI.Validation.Tests/Models/SampleViewModel.cs
  src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs
  src/ReactiveUI.Validation/Extensions/ValidatableViewModelExtensions.cs
  src/ReactiveUI.Validation/Extensions/ViewForExtensions.cs
  src/ReactiveUI.Validation/Platforms/Android/ViewForExtensions.cs
  src/ReactiveUI.Validation/ValidationBindings/ValidationBinding.cs
Labels: enhancement

#120 refactor: Update the LoginApp to use Newer ValidationRule Overloads
  samples/LoginApp.Avalonia/Views/SignUpView.xaml
  samples/LoginApp/ViewModels/SignUpViewModel.cs
Labels: enhancement

#122 refactor: Deprecate Generic IValidatesProperties<T>
  src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt
  src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt
  src/ReactiveUI.Validation.Tests/ObservableValidationTests.cs
  src/ReactiveUI.Validation.Tests/ReactiveUI.Validation.Tests.csproj
  src/ReactiveUI.Validation/Components/Abstractions/IPropertyValidationComponent.cs
  src/ReactiveUI.Validation/Components/Abstractions/IValidatesProperties.cs
  src/ReactiveUI.Validation/Components/BasePropertyValidation.cs
  src/ReactiveUI.Validation/Components/ModelObservableValidation.cs
  src/ReactiveUI.Validation/Components/ObservableValidation.cs
  src/ReactiveUI.Validation/Extensions/ValidatesPropertiesExtensions.cs
  src/ReactiveUI.Validation/Extensions/ValidationContextExtensions.cs
Labels: enhancement

#125 housekeeping: Release version 1.7
  version.json
Labels: release

#131 Update README.md
  README.md
Labels: hacktoberfest-accepted

#133 housekeeping: Update README.md
  README.md
Labels: hacktoberfest-accepted

#140 housekeeping: Release version 1.8
  version.json
Labels: release

#144 Fixes ReactiveValidationObject NullReferenceException and enhances performance and thread-safety of ValidationText
  src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.net472.approved.txt
  src/ReactiveUI.Validation.Tests/API/ApiApprovalTests.ValidationProject.netcoreapp3.1.approved.txt
  src/ReactiveUI.Validation.Tests/ValidationBindingTests.cs
  src/ReactiveUI.Validation.Tests/ValidationTextTests.cs
  src/ReactiveUI.Validation/Collections/ValidationText.cs
  src/ReactiveUI.Validation/Components/BasePropertyValidation.cs
  src/ReactiveUI.Validation/Components/ModelObservableValidation.cs
  src/ReactiveUI.Validation/Components/ObservableValidation.cs
  src/ReactiveUI.Validation/Contexts/ValidationContext.cs
  src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs
  src/ReactiveUI.Validation/States/ValidationState.cs
  src/ReactiveUI.Validation/TemplateGenerators/PropertyValidationGenerator.cs
  src/ReactiveUI.Validation/TemplateGenerators/PropertyValidationGenerator.tt
Labels: hacktoberfest-accepted

#150 housekeeping: Correct ValidationText Error Message
  src/ReactiveUI.Validation/Collections/ValidationText.cs
Labels: release
